import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import 'package:catalyst_app/models/team_model.dart';
import 'package:catalyst_app/features/teams/presentation/providers/team_provider.dart';
import 'package:catalyst_app/features/auth/presentation/providers/auth_provider.dart';
import 'package:catalyst_app/shared/widgets/loading_overlay.dart';
import 'package:catalyst_app/shared/widgets/animated_pressable.dart';

import 'package:flutter/services.dart';

class CreateTeamScreen extends ConsumerStatefulWidget {
  final String hackathonId;

  const CreateTeamScreen({super.key, required this.hackathonId});

  @override
  ConsumerState<CreateTeamScreen> createState() => _CreateTeamScreenState();
}

class _CreateTeamScreenState extends ConsumerState<CreateTeamScreen> {
  final _formKey = GlobalKey<FormState>();
  final _nameController = TextEditingController();
  final _descController = TextEditingController();
  final _skillsController = TextEditingController();
  final _sizeController = TextEditingController();
  String _commitment = 'Full';
  String _availability = 'Weekends';

  Future<void> _submit() async {
    if (!_formKey.currentState!.validate()) return;

    final user = ref.read(authProvider).user;
    if (user == null) return;

    final team = Team(
      id: '', // Generated by server
      hackathonId: widget.hackathonId,
      creatorId: user.id,
      name: _nameController.text,
      description: _descController.text,
      requiredSkills: _skillsController.text.split(',').map((e) => e.trim()).toList(),
      maxMembers: int.tryParse(_sizeController.text),
      commitmentLevel: _commitment,
      availability: _availability,
      createdAt: DateTime.now(),
    );

    try {
      await ref.read(teamProvider.notifier).createTeam(team);
      HapticFeedback.lightImpact();
      if (mounted) {
        ref.invalidate(userTeamProvider(widget.hackathonId));
        context.go('/home');
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text(e.toString()),
            backgroundColor: Colors.redAccent,
            behavior: SnackBarBehavior.floating,
          ),
        );
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    final state = ref.watch(teamProvider);

    return LoadingOverlay(
      isLoading: state.isLoading,
      message: 'Creating Team...',
      child: Scaffold(
        appBar: AppBar(title: const Text('Create Team')),
        body: Form(
          key: _formKey,
          child: ListView(
            padding: const EdgeInsets.all(16),
          children: [
            TextFormField(
              controller: _nameController,
              decoration: const InputDecoration(labelText: 'Team Name'),
              validator: (v) => v!.isEmpty ? 'Name required' : null,
            ),
            const SizedBox(height: 16),
            TextFormField(
              controller: _sizeController,
              decoration: const InputDecoration(labelText: 'Max Team Size'),
              keyboardType: TextInputType.number,
              validator: (v) => v!.isEmpty ? 'Size required' : null,
            ),
            const SizedBox(height: 16),
            TextFormField(
              controller: _skillsController,
              decoration: const InputDecoration(labelText: 'Required Skills (comma separated)'),
              validator: (v) => v!.isEmpty ? 'Skills required' : null,
            ),
            const SizedBox(height: 16),
            DropdownButtonFormField<String>(
            initialValue: _commitment,
              decoration: const InputDecoration(labelText: 'Commitment Level'),
              items: ['Full', 'Medium', 'Low'].map((e) => DropdownMenuItem(value: e, child: Text(e))).toList(),
              onChanged: (v) => setState(() => _commitment = v!),
            ),
            const SizedBox(height: 16),
            DropdownButtonFormField<String>(
            initialValue: _availability,
              decoration: const InputDecoration(labelText: 'Availability'),
              items: ['Weekends', 'Evenings', 'Anytime'].map((e) => DropdownMenuItem(value: e, child: Text(e))).toList(),
              onChanged: (v) => setState(() => _availability = v!),
            ),
            const SizedBox(height: 16),
            TextFormField(
              controller: _descController,
              decoration: const InputDecoration(labelText: 'Team Description'),
              maxLines: 3,
            ),
            const SizedBox(height: 32),
            AnimatedPressable(
              onTap: _submit,
              child: Container(
                width: double.infinity,
                padding: const EdgeInsets.symmetric(vertical: 16),
                decoration: BoxDecoration(
                  color: Colors.blue,
                  borderRadius: BorderRadius.circular(12),
                ),
                child: const Center(
                  child: Text(
                    'Create Team',
                    style: TextStyle(color: Colors.white, fontWeight: FontWeight.bold),
                  ),
                ),
              ),
            ),
          ],
        ),
      ),
    ),
  );
}
}
